disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - .build
  - DerivedData

identifier_name:
  min_length: 1
  max_length: 60

type_name:
  min_length: 3
  max_length: 40

function_body_length:
  warning: 100
  error: 150

