name: {{PROJECT_NAME}}
options:
  bundleIdentifierPrefix: com.brx.{{PROJECT_NAME_LOWER}}
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
targets:
  {{PROJECT_NAME}}:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
        type: group
    settings:
      base:
        PRODUCT_NAME: {{PROJECT_NAME}}
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.{{PROJECT_NAME_LOWER}}
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        ENABLE_BITCODE: NO
    scheme:
      testTargets: []
      gatherCoverageData: false
      coverageTargets: []
      build:
        targets:
          {{PROJECT_NAME}}: all
