name: WatchCompanion
options:
  bundleIdPrefix: com.brx
targets:
  WatchCompanion:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_NAME: WatchCompanion
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.WatchCompanion
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
