name: WatchCounter
options:
  bundleIdPrefix: com.brx
targets:
  WatchCounter:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_NAME: WatchCounter
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.WatchCounter
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        WKCompanionAppBundleIdentifier: com.brx.WatchCounter.watchkitapp
  WatchCounter WatchKit App:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - WatchKitApp
    resources:
      - WatchKitApp/Resources
    settings:
      base:
        PRODUCT_NAME: WatchCounter WatchKit App
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.WatchCounter.watchkitapp
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.brx.WatchCounter
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
  WatchCounter WatchKit Extension:
    type: app-extension
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - WatchKitExtension
    resources:
      - WatchKitExtension/Resources
    settings:
      base:
        PRODUCT_NAME: WatchCounter WatchKit Extension
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.WatchCounter.watchkitapp.watchkitextension
        INFOPLIST_KEY_WKAppBundleIdentifier: com.brx.WatchCounter.watchkitapp
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
