name: {{NAME}}
options:
  bundleIdPrefix: {{BUNDLE_ID}}
  deploymentTarget:
    watchOS: 10.0
targets:
  {{NAME}}:
    type: application.watchapp2
    platform: watchOS
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: {{BUNDLE_ID}}
      INFOPLIST_FILE: Sources/Info.plist
      TARGETED_DEVICE_FAMILY: 4
schemes:
  {{NAME}}:
    build:
      targets:
        {{NAME}}: all
    run:
      config: Debug

