name: FinalTest
options:
  bundleIdentifierPrefix: com.brx.finaltest
targets:
  FinalTest:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.brx.finaltest