name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-14
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Build Release
        run: make build
      
      - name: Create Archive
        run: |
          cd .build/release
          # Remove 'v' prefix from version for filename
          VERSION=${GITHUB_REF_NAME#v}
          echo "Creating archive: brx-$VERSION-macos.tar.gz"
          ls -la
          tar -czf brx-$VERSION-macos.tar.gz BRX
          ls -la
          mv brx-$VERSION-macos.tar.gz ../../
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Archive created, checking root directory:"
          ls -la ../../
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: brx-${{ env.VERSION }}-macos.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

