name: FitTrackerWatch
options:
  bundleIdPrefix: com.brx
targets:
  FitTrackerWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_NAME: FitTrackerWatch
        PRODUCT_BUNDLE_IDENTIFIER: com.brx.FitTrackerWatch
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic